apiVersion: v1
kind: Service
metadata:
    labels:
        app: node
    name: node
spec:
    ports:
    -   port: 80
        targetPort: 3000
    selector:
        app: node
    externalIPs:
      - 172.17.4.99
