apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
        app: node
    name: node
spec:
    replicas: 5
    selector:
        matchLabels:
            app: node
    template:
        metadata:
            labels:
                app: node
        spec:
            containers:
            -   command:
                - /app/run-node.sh
                image: tanmaig/express-example:k8s2
                name: node
                ports:
                -   containerPort: 3000
